version: '3'
services:
  backend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - 6082:6082
    depends_on:
      - mongodb
    environment:
      VIRTUAL_HOST: backend.dev
    networks:
      - fullstack

  mongodb:
    image: mongo:latest
    # environment:
    #   - MONGO_INITDB_DATABASE=eb_database
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=iWzW22ePDooMBN
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db:rw
      - ./mongo/configdb:/mongo/configdb:rw
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fullstack 

networks:
  fullstack:
    driver: bridge