FROM node:18-alpine
WORKDIR /app/
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./app/
COPY . .
#RUN yarn install --legacy-peer-deps
RUN npm cache clean --force
RUN npm i nodemon
RUN npm install -g npm@latest && npm install --legacy-peer-deps
CMD ["npm", "start", "dev"]
